---
roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.mysql
    version: 3.3.0
  - name: cchurch.virtualenv
    version: 0.6.5
  - name: nginxinc.nginx_config
    version: 0.1.0
  - name: nginxinc.nginx
    version: 0.17.0