"""Remove unique from publisher url

Revision ID: 3d6d7472dd71
Revises: 4ebb0f82b06e
Create Date: 2018-06-02 22:45:25.565175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6d7472dd71'
down_revision = '4ebb0f82b06e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('url', table_name='publisher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('url', 'publisher', ['url'], unique=True)
    # ### end Alembic commands ###
