"""Add note for authors

Revision ID: 4ebb0f82b06e
Revises: 9ac570527f40
Create Date: 2018-06-01 22:10:02.933508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ebb0f82b06e'
down_revision = '9ac570527f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('note', sa.Text(collation='utf8_general_ci'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'note')
    # ### end Alembic commands ###
