"""Add book volume num

Revision ID: 9ac570527f40
Revises: 83c4a51fd7d2
Create Date: 2018-05-25 15:10:46.197991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac570527f40'
down_revision = '83c4a51fd7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('volume', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'volume')
    # ### end Alembic commands ###
